### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ROS XMLRPC Error: no provider

### ISSUE THREAD

**Issue by jmachuca77** [RethinkRobotics-opensource/rosnodejs#176]
I have a nodejs program that calls a ros service periodically. However at boot my program starts running before the ros node is started so the the service call happens before the ros master is up. This causes the following error in rosnodejs:
```
(node:21258) UnhandledPromiseRejectionWarning: Error: ROS XMLRPC Error: no provider
    at /home/aion/GitHub/workers/worker_vehicle_manager/node_modules/rosnodejs/dist/utils/XmlrpcClient.js:28:25
    at /home/aion/GitHub/workers/worker_vehicle_manager/node_modules/xmlrpc/lib/client.js:130:9
    at Deserializer.callback (/home/aion/GitHub/workers/worker_vehicle_manager/node_modules/xmlrpc/lib/deserializer.js:42:7)
    at Deserializer.onDone (/home/aion/GitHub/workers/worker_vehicle_manager/node_modules/xmlrpc/lib/deserializer.js:92:12)
    at SAXStream.emit (events.js:314:20)
    at SAXStream.EventEmitter.emit (domain.js:483:12)
    at SAXParser.onend (/home/aion/GitHub/workers/worker_vehicle_manager/node_modules/sax/lib/sax.js:190:10)
    at emit (/home/aion/GitHub/workers/worker_vehicle_manager/node_modules/sax/lib/sax.js:624:35)
    at end (/home/aion/GitHub/workers/worker_vehicle_manager/node_modules/sax/lib/sax.js:667:5)
    at SAXParser.end (/home/aion/GitHub/workers/worker_vehicle_manager/node_modules/sax/lib/sax.js:154:24)
    at SAXStream.end (/home/aion/GitHub/workers/worker_vehicle_manager/node_modules/sax/lib/sax.js:248:18)
    at IncomingMessage.onend (_stream_readable.js:683:10)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

(node:21258) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21258) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I would like to prevent this error from being thrown but I am not sure where this would need to be done.

**Comment by chris-smith** [comment]
Are you calling `rosnodejs.initNode` and waiting for the promise to resolve? As long as you're waiting for that to complete before calling the service then rosnodejs should be connected to the ROS master.

**Comment by chris-smith** [comment]
Closing for now. Feel free to re-open.
